import { useEffect, useState } from "react";
import "./Home.css";
import axios from "axios";
import { Card } from "../../components";
import { Link } from "react-router-dom";

const Home = () => {
  const [posts, setPosts] = useState([]);
  const [isLoading, setIsLoading] = useState(false);

  useEffect(() => {
    const fetchData = async () => {
      const accessToken = localStorage.getItem("accessToken");
      setIsLoading(true);
      await axios
        .get("http://127.0.0.1:8000/api/posts", {
          headers: {
            Authorization: `Bearer ${accessToken}`,
            "Content-Type": "application/json",
          },
        })
        .then((response) => {
          setPosts(response.data);
          setIsLoading(false);
        })
        .catch((err) => console.log(err.message));
    };

    fetchData();
  }, []);

  return (
    <div className="home">
      <h1>The Community Showcase</h1>
      <p>
        Browse through a collection of imaginative and visually stunning images
        generated by DALL-E AI
      </p>

      {isLoading ? (
        <div className="load">
          <div className="one"></div>
          <div className="two"></div>
          <div className="three"></div>
        </div>
      ) : (
        <div className="posts">
          {posts.map((post) => (
            <Link key={post.id} to={`posts/${post.id}/show`}>
              <Card post={post} />
            </Link>
          ))}
        </div>
      )}
    </div>
  );
};

export default Home;
